version: "3.7"

services:
  mongo:
    image: mongo:4.4.18
    container_name: mongodb
    network_mode: host
    restart: always
    #ports de mongo
    
  express:
    build:
      context: ./app/api
      dockerfile: Dockerfile-express
    container_name: express
    network_mode: host
    restart: always
    #ports:
    #  - "3000:3000"
    volumes:
      - ./app/api:/app/api
    depends_on:
      - mongo
    user: "1000:1000"

  angular:
    build:
      context: ./app/client
      dockerfile: Dockerfile-angular
    container_name: angular
    network_mode: host
    restart: always
    #ports:
    #  - "4200:4200"
    volumes:
      - ./app/client:/app/client
    depends_on:
      - express
    user: "1000:1000"